/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishesRouteImport } from './routes/wishes'
import { Route as IndexRouteImport } from './routes/index'

const WishesRoute = WishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wishes': typeof WishesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wishes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wishes'
  id: '__root__' | '/' | '/wishes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WishesRoute: typeof WishesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishes': {
      id: '/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof WishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WishesRoute: WishesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
